### ISSUE TITLE
Warnings and crash when using the new C frontend with joern-scan on VLC

### ISSUE THREAD

**Issue by johannescoetzee** [ShiftLeftSecurity/codepropertygraph#1361]
When running joern-scan on the VLC repo using the new frontend, the following warnings were shown in the log file. These warnings were not emitted when running joern-scan using the fuzzy frontend.

```
2021-08-18 09:00:07.711 WARN CustomFileContentProvider: Include file not found: '/home/johannes/code/test_repos/vlc/compat/test/config.h'
```
```
2021-08-18 09:00:08.038 WARN AstCreator: Node 'CASTSimpleDeclaration' not handled yet!
  Code: 'LIBVLC_API'
  File: '/home/johannes/code/test_repos/vlc/include/vlc/libvlc_media.h'
  Line: 701
  ```
  
  ```
  Adding default overlays to base CPG
2021-08-18 09:00:54.328 WARN Linker: Invalid AST_PARENT_TYPE=Optional[<empty>]; astChild LABEL=METHOD; astChild FULL_NAME=Optional[VLCVideo.VLCVideo.anonymous_lambda_0]
2021-08-18 09:00:54.328 WARN Linker: Could not create edge. Source lookup failed. edgeType=AST, srcNodeType=<empty>, srcFullName=<empty>, dstNodeType=METHOD, dstNodeId=1005246
```

```
2021-08-18 09:00:55.145 WARN Linker: Could not create edge. Destination lookup failed. edgeType=EVAL_TYPE, srcNodeType=METHOD_REF, srcNodeId=1005366, dstNodeType=TYPE, dstFullName=VLCVideo.VLCVideo.anonymous_lambda_0
```

```
2021-08-18 09:00:59.574 WARN MemberAccessLinker: Error while obtaining IDENTIFIER associated to member access at io.shiftleft.codepropertygraph.generated.nodes.Call[label=CALL; id=1005157] Reason: member/field access-style operators need two arguments
```

```
2021-08-18 09:01:24.762 WARN AccessPathUsage$: Missing first argument on call io.shiftleft.codepropertygraph.generated.nodes.Call[label=CALL; id=1010985].
```

The run then ended with a crash due to the following error:

```
Exception in thread "main" java.lang.AssertionError: script errored: 
	at io.shiftleft.console.BridgeBase.runScript(BridgeBase.scala:356)
	at io.shiftleft.console.BridgeBase.$anonfun$runPlugin$4(BridgeBase.scala:242)
	at io.shiftleft.console.BridgeBase.$anonfun$runPlugin$4$adapted(BridgeBase.scala:241)
	at io.shiftleft.console.BridgeBase.$anonfun$withTemporaryScript$1(BridgeBase.scala:198)
	at io.shiftleft.console.BridgeBase.$anonfun$withTemporaryScript$1$adapted(BridgeBase.scala:195)
	at better.files.Dispose.apply(Dispose.scala:82)
	at better.files.Dispose.foreach(Dispose.scala:104)
	at better.files.File$.usingTemporaryDirectory(File.scala:1371)
...
Caused by: scala.MatchError: io.shiftleft.codepropertygraph.generated.nodes.File[label=FILE; id=2902473] (of class io.shiftleft.codepropertygraph.generated.nodes.File)
	at io.shiftleft.semanticcpg.language.nodemethods.CfgNodeMethods$.walkUpContains$extension(CfgNodeMethods.scala:116)
	at io.shiftleft.semanticcpg.language.nodemethods.CfgNodeMethods$.method$extension(CfgNodeMethods.scala:104)
	at io.shiftleft.semanticcpg.language.nodemethods.IdentifierMethods$.location$extension(IdentifierMethods.scala:14)
...
```

The overall result of this was that joern-scan using the new frontend found significantly fewer vulnerabilities than using the fuzzy frontend (~22500 findings with the fuzzy frontend vs ~3500 with the new). Some of the fuzzy findings are likely false positives, but given the large difference in the number of findings, it seems likely that joern-scan with the new frontend is missing legitimate vulnerabilities.

Some more info:
* Used joern commit `1052cafbd3de1ef3953cf58c29ed5aec8233c6a1` (tip of jcoetzee/all-queries branch), but with `cpgVersion = "1.3.287"
* Installed queries with `./joern-scan --updatedb`, so those would be the latest release
* Used `videolan/vlc` repo with commit `fcba92731ae5651fb4b8707fa07c3ee425e09929` checked out (tip of master at time of checkout). 
* Ran joern-scan with `/joern-scan --overwrite --all-queries --language newc ../../test_repos/vlc `
* Full log: [new_vlc.log.gz](https://github.com/ShiftLeftSecurity/codepropertygraph/files/7005612/new_vlc.log.gz)

**Comment by johannescoetzee** [comment]
I reran the test using the `codepropertygraph` changes from https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1360, and that seems to have addressed the third warning I mentioned in the issue, i.e.
```
2021-08-18 09:00:54.328 WARN Linker: Invalid AST_PARENT_TYPE=Optional[<empty>]; astChild LABEL=METHOD; astChild FULL_NAME=Optional[VLCVideo.VLCVideo.anonymous_lambda_0]
2021-08-18 09:00:54.328 WARN Linker: Could not create edge. Source lookup failed. edgeType=AST, srcNodeType=<empty>, srcFullName=<empty>, dstNodeType=METHOD, dstNodeId=1005246
```

The rest of the warnings are still there, as well as the eventual crash. The number of findings also did not change.

**Comment by ursachec** [comment]
@max-leuthaeuser looks like this one's for you

**Comment by max-leuthaeuser** [comment]
I am already on it.

**Comment by johannescoetzee** [comment]
Running `./joern-scan --language newc ../../test_repos/vlc --tags <TAG>` for any specific tag doesn't result in the same crash, but `./joern-scan --language newc ../../test_repos/vlc --tags all` does. The crash is probably due to a specific query broken

**Comment by johannescoetzee** [comment]
```
./joern-scan --language newc ../../test_repos/vlc --tags default,badfn,metrics,integers,uaf,setxid,badimpl,posix,race-condition,sql-injection,strings,xss | wc
  19669  160657 2582127
  ```
  Only running queries with tags gives ~20k findings, so much closer to fuzzyc.

**Comment by max-leuthaeuser** [comment]
The issues within the MemberAccessLinker and AccessPathUsage are also known to me. They are due to a proper CallExpression handling (this argument, call receiver, etc.). Its already on my TODO list.

**Comment by johannescoetzee** [comment]
The crash seems to be triggered by the simple-constant-detection query:
```
({cpg.assignment
  .groupBy(_.argument.order(1).code.l)
  .flatMap {
    case (_: List[String], as: Traversal[Assignment]) => Option(as.l)
    case _                                            => Option.empty
  }
  .filter(_.size == 1)
  .flatMap {
    case as: List[Assignment] =>
      Option(as.head.argument.head, as.head.argument.l.head.typ.l)
    case _ => Option.empty
  }
  .filter {
    case (_: Identifier, ts: List[Type]) =>
      ts.nonEmpty &&
        ts.head.namespace.l.exists { x =>
          x.name.contains("<global>")
        } &&
        !ts.head.fullName.contains("[]")
    case _ => false
  }
  .flatMap {
    case (i: Identifier, _: List[Type]) => Option(i)
    case _                              => Option.empty
  }}).l
  ```

**Comment by johannescoetzee** [comment]
Details about an issue that explains some of the discrepancies between findings using the new and old frontends can be found here: https://github.com/joernio/joern/issues/577. It looks like, when using the new frontend, joern-scan incorrectly reports twice for functions defined in header files. I opened that issue in the joern repo, since I'm not sure where the fix for it will happen.

**Comment by max-leuthaeuser** [comment]
Running c2cpg on VLC does not crash anymore and the query in question also runs fine.
Closing this.
(other warnings, e.g., header files missing and unsupported AST nodes are tackled separately)
